apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: cadvisor
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: cadvisor

  template:
    metadata:
      labels:
        app: cadvisor

    spec:
      hostNetwork: true
      hostPID: true

      containers:

      - name: cadvisor

        image: gcr.io/cadvisor/cadvisor:v0.49.1

        ports:
        - containerPort: 8080

        securityContext:
          privileged: true

        volumeMounts:

        - name: rootfs
          mountPath: /rootfs
          readOnly: true

        - name: varrun
          mountPath: /var/run

        - name: sys
          mountPath: /sys
          readOnly: true

        - name: docker
          mountPath: /var/lib/docker
          readOnly: true

        - name: disk
          mountPath: /dev/disk
          readOnly: true

      volumes:

      - name: rootfs
        hostPath:
          path: /

      - name: varrun
        hostPath:
          path: /var/run

      - name: sys
        hostPath:
          path: /sys

      - name: docker
        hostPath:
          path: /var/lib/docker

      - name: disk
        hostPath:
          path: /dev/disk