apiVersion: v1
kind: ConfigMap

metadata:
  name: velocore-config
  namespace: { { .Values.namespace } }

data:
  NODE_ENV: production
  PORT: "8080"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: { { .Values.postgres.auth.database | quote } }
  LOKI_URL: http://loki:3100