apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:

        - name: grafana
          image: grafana/grafana:11.1.0

          ports:
            - containerPort: 3000

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin123

          volumeMounts:

            - name: storage
              mountPath: /var/lib/grafana

            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources

            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards

            - name: platform-dashboard
              mountPath: /var/lib/grafana/dashboards/platform

            - name: user-dashboard
              mountPath: /var/lib/grafana/dashboards/user

      volumes:

        - name: storage
          persistentVolumeClaim:
            claimName: grafana-storage

        - name: datasource
          configMap:
            name: grafana-datasources

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: platform-dashboard
          configMap:
            name: grafana-platform-dashboard

        - name: user-dashboard
          configMap:
            name: grafana-user-dashboard