apiVersion: v1
kind: Secret

metadata:
  name: velocore-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  # ==========================================
  # Server
  # ==========================================
  PORT: "8080"
  RUNTIME_ENGINE: "kubernetes"
  PUBLIC_URL: "http://localhost"
  FRONTEND_URL: "http://localhost:3000"

  # ==========================================
  # PostgreSQL
  # ==========================================
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "devplatformdb"
  DB_USER: "postgres"
  DB_PASSWORD: "Stna@2234"

  # ==========================================
  # Redis
  # ==========================================
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # ==========================================
  # Kubernetes
  # ==========================================
  K8S_STORAGE_CLASS: "local-path"
  SKIP_K8S_RECOVERY: "true"

  # ==========================================
  # Security
  # ==========================================
  BLOCK_ON_SECRETS: "false"
  BLOCK_ON_CRITICAL: "false"

  # ==========================================
  # GitHub OAuth
  # ==========================================
  GITHUB_CLIENT_ID: "Ov23liIsEEytlU2uOkJA"
  GITHUB_CLIENT_SECRET: "8297f37e4a027a12911574920cd5666ed1d54756"

  # ==========================================
  # Encryption
  # ==========================================
  ENCRYPTION_KEY: "64cc69dc867f70b4f8d55ff2fc57404a3f12445e99d3e8bb81e7d2a58d626a5b"
  JWT_SECRET: "83fa8b12f68903da76a5df491bc1e3e5c9428ad3ef9834bd8e32c84bc2251a29"