server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    #
    # Grafana
    #
   #
# Grafana
#

location ^~ /d/ {
    proxy_pass http://grafana:3000;
    proxy_set_header Host $host;
}

location ^~ /public/ {
    proxy_pass http://grafana:3000;
    proxy_set_header Host $host;
}

location ^~ /avatar/ {
    proxy_pass http://grafana:3000;
}

location ^~ /login {
    proxy_pass http://grafana:3000;
}

location ^~ /logout {
    proxy_pass http://grafana:3000;
}

location ^~ /api/live/ {
    proxy_pass http://grafana:3000;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

location ^~ /api/frontend-metrics {
    proxy_pass http://grafana:3000;
}

location ^~ /api/search {
    proxy_pass http://grafana:3000;
}

location ^~ /api/dashboards {
    proxy_pass http://grafana:3000;
}

location ^~ /api/datasources {
    proxy_pass http://grafana:3000;
}

location ^~ /api/prometheus {
    proxy_pass http://grafana:3000;
}

location ^~ /api/annotations {
    proxy_pass http://grafana:3000;
}

    #
    # React
    #
    location / {
        try_files $uri /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}