const crypto = require('crypto');
require('dotenv').config();

const ALGORITHM = 'aes-256-gcm';
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY; 

if (!ENCRYPTION_KEY || ENCRYPTION_KEY.length !== 64) {
  throw new Error('❌ Critical Security Defect: ENCRYPTION_KEY must be a valid 32-byte hex string (64 characters long).');
}

/**
 * Encrypts plain text strings into safe database ciphertext hex arrays
 */
function encrypt(text) {
  // Generate a cryptographically secure, random 12-byte Initialization Vector (IV) for every transaction
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY, 'hex'), iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  // Extract the secure authentication tag generated by GCM mode
  const authTag = cipher.getAuthTag().toString('hex');
  
  // Return all three vital tracking components joined by a safe colon separator delimiter
  return `${iv.toString('hex')}:${encrypted}:${authTag}`;
}

/**
 * Decrypts structured database ciphertext arrays back into readable strings
 */
function decrypt(ciphertext) {
  const [ivHex, encryptedHex, authTagHex] = ciphertext.split(':');
  
  if (!ivHex || !encryptedHex || !authTagHex) {
    throw new Error('Corrupted Ciphertext Array Vector Structure.');
  }

  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY, 'hex'), iv);
  
  decipher.setAuthTag(authTag);
  
  let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
}

module.exports = { encrypt, decrypt };