deploymentId: ""

namespace: ""

slot: blue

type: ""

framework: ""

image:
  repository: ""

container:
  port: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: ""

env: {}

podAnnotations: {}

serviceAccount:
  create: true
  name: ""

resources: {}