deploymentId: test-app

namespace: default

slot: blue

type: ""

framework: ""

replicas: 1

image:
  repository: ""

container:
  port: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  host: ""

env: {}

healthCheck:
  path: /health

resources: {}

serviceAccount:
  create: true
  name: velocore-app

vault:
  enabled: false
  role: ""
  secretPath: ""