deploymentId: "test"

namespace: "default"

slot: blue

type: ""

framework: ""

replicas: 1

image:
  repository: ""

container:
  port: 8080

service:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: traefik
  host: ""

backend:
  enabled: false
  serviceName: ""
  servicePort: 8080  

env: {}

healthCheck:
  enabled: true
  path: /health

podAnnotations: {}

serviceAccount:
  create: true
  name: ""

resources: {}