apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: velocore
  namespace: argocd

spec:

  project: velocore

  source:
    repoURL: https://github.com/shaurya-sehgal5/VeloCore.git
    targetRevision: main
    path: deploy/helm

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: velocore

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true