{{- if (.Values.ingress | default dict).enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.deploymentId }}
  namespace: {{ .Values.namespace }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ .Values.ingress.host }}

      http:
        paths:

          {{- if .Values.backend.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.serviceName }}
                port:
                  number: {{ .Values.backend.servicePort }}
          {{- end }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deploymentId }}
                port:
                  number: {{ .Values.service.port }}

{{- end }}