{{- if (.Values.service | default dict).enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.deploymentId }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.deploymentId }}
    slot: {{ .Values.slot }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP

  type: {{ .Values.service.type }}

{{- end }}