name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-helm:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Backend Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${GITHUB_SHA}/" deploy/helm/values.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add deploy/helm/values.yaml

          git diff --cached --quiet && exit 0

          git commit -m "chore: update image tag to ${GITHUB_SHA}"

      - name: Push Changes
        run: |
          git push origin main